language: objective-c
osx_image: xcode8.3
before_install:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - echo -e "machine github.com\n  login fastlane-mathandoro\n  password $CI_USER_PASSWORD" >> ~/.netrc
    - gem update fastlane --no-ri --no-rdoc --no-document
    - export MATCH_KEYCHAIN_NAME=ios-build.keychain
    - fastlane setup_keychain
script:
    - chmod +x travis/script.sh && ./travis/script.sh
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x travis/upload_beta.sh && travis_wait 30 sh $TRAVIS_BUILD_DIR/travis/upload_beta.sh
  on:
    branch: master