language: objective-c
osx_image: xcode8.3
before_install:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - echo -e "machine github.com\n  login fastlane-mathandoro\n  password $CI_USER_PASSWORD" >> ~/.netrc
    - gem update fastlane --no-ri --no-rdoc --no-document
script: chmod +x travis/script.sh && ./travis/script.sh