# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do
    # increment_build_number
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "build dev"
  lane :build_dev do
    match(type: "appstore",
      app_identifier: "com.mathandoro.coachplus.dev")
    gym(scheme: "CoachPlusDev")
  end

  lane :setup_keychain do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: "travis",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end

  lane :set_build_number do
    increment_build_number
    commit_version_bump(message: '***NO_CI*** Bump version', force: true)
    sh "git remote add origin2 git@github.com:coach-plus/ios.git"
    push_to_git_remote(
      remote: "origin2",
      remote_branch: "master"
    )
  end

  lane :build_beta do
    match(type: "appstore",
      app_identifier: "com.mathandoro.coachplus.beta",
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: "travis")
    disable_automatic_code_signing(path: "CoachPlus.xcodeproj")
    gym(scheme: "CoachPlusBeta") # Build your app - more options available
  end

  lane :upload_beta do
    pilot(app_identifier: "com.mathandoro.coachplus.dev", ipa: "CoachPlusDev.ipa")
  end

  lane :build_production do
    match(type: "appstore",
      app_identifier: "com.mathandoro.coachplus",
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: "travis")
    disable_automatic_code_signing(path: "CoachPlus.xcodeproj")
    gym(scheme: "CoachPlus")
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end